services:
  web:
    build:
      context: ./web
    restart: always
    ports:
      - 8081:8081
    volumes:
      - ./:/usr/web
      - /usr/web/node_modules

  api:
    build:
      context: ./api
    restart: always
    ports:
      - 8082:8082
    depends_on:
      - mongo
    volumes:
      - ./:/usr/api
      - /usr/api/node_modules
    environment:
      - HTTP_PORT=8082
      - MONGO_DB_HOST=mongo
      - MONGO_DB_PORT=27017
      - MONGO_DB_DATABASE=chat0

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db

volumes:
  mongo:
